version: "3"

networks:
  stack_ponte:
    external: true

services:

  frontend_ubyus:
    container_name: "frontend_ubyus"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "${PATHCLIENTES}/ubyusnewversion/frontend:/app"
    command: "yarn dev"
    networks:
      - stack_ponte
    ports:
      - "3082:3000"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontubyus.rule=Host(`frontubyus.${DOMAIN}`)
      - traefik.http.services.frontubyus.loadbalancer.server.port=3000
